import {
  LOCKER_APPLICATION_PHASE,
  type LockerApplicationPhase,
} from './lockerApplicationPhase';

export const DEFAULT_LOCKER_APPLICATION_PERIOD_TITLE = '사물함 신청 기간 안내';

export const LOCKER_APPLICATION_PERIOD_TITLE = {
  [LOCKER_APPLICATION_PHASE.READY]: DEFAULT_LOCKER_APPLICATION_PERIOD_TITLE,
  [LOCKER_APPLICATION_PHASE.APPLY]: DEFAULT_LOCKER_APPLICATION_PERIOD_TITLE,
  [LOCKER_APPLICATION_PHASE.EXTEND]: '사물함 연장 기간 안내',
  [LOCKER_APPLICATION_PHASE.CLOSED]: DEFAULT_LOCKER_APPLICATION_PERIOD_TITLE,
} as const satisfies Record<LockerApplicationPhase, string>;
