packages:
  - "apps/*"
  - "packages/*"
  - "packages/config/*"
  - "packages/design-system/*"

catalogs:
  default:
    zustand: ^5.0.0
    react: 19.2.0
    react-dom: 19.2.0
    next: 16.0.0
    "@tanstack/react-query": ^5.0.00
