export const ALUMNI_CONTACTS_EDIT_FORM_MAX_LENGTH = {
  DESCRIPTION: 100,
  SOCIAL_LINKS: 10,
  USER_TECH_STACK: 10,
  USER_CAREER: 10,
  USER_PROJECT: 10,
  USER_INTEREST_TECH: 10,
  USER_INTEREST_DOMAIN: 10,
  CAREER_DESCRIPTION: 50,
  PROJECT_DESCRIPTION: 50,
} as const;
