export const ALUMNI_CONTACTS_EDIT_FORM_MAX_LENGTH = {
  DESCRIPTION: 100,
  CAREER_DESCRIPTION: 50,
  PROJECT_DESCRIPTION: 50,
} as const;

export const ALUMNI_CONTACTS_EDIT_FORM_MAX_LIMIT = {
  SOCIAL_LINKS: 10,
} as const;
