export const COPY = Object.freeze({
  NEW_NOTIFICATION_TITLE: '새 알림',
  QUICK_MENU_MEETINGROOM: '팀플룸 예약',
  QUICK_MENU_CAFETERIA: '학식 메뉴',
  QUICK_MENU_LOCKER: '사물함 예약',
  MAIN_SCHEDULE_TITLE: '주요 일정',
  EMPTY_SCHEDULE: '이 달의 일정이 없어요',
  ENTIRE_SCHEDULE: '일정 전체보기',
  CEREMONY_REGISTER: '경조사 신청하기',
  CEREMONY_REGISTER_DESCRIPTION: `결혼, 장례, 졸업, 행사소식 등\n전체 알림을 보내보세요!`,
  CEREMONY_VIEW_ALL: '경조사 전체보기',
  EMPTY_CEREMONY: '곧 다가올 경조사가 없어요',
  HOME_CEREMONY_TITLE: '곧 다가올 경조사',
  MONTHLY_SCHEDULE_TITLE: '이 달의 주요 일정',
} as const);
