/* 신고 사유 */
export const REPORT_REASON = {
  OFF_TOPIC: 'OFF_TOPIC',
  SPAM_AD: 'SPAM_AD',
  ABUSE_LANGUAGE: 'ABUSE_LANGUAGE',
  COMMERCIAL_AD: 'COMMERCIAL_AD',
  INAPPROPRIATE_CONTENT: 'INAPPROPRIATE_CONTENT',
  FRAUD_IMPERSONATION: 'FRAUD_IMPERSONATION',
  POLITICAL_CONTENT: 'POLITICAL_CONTENT',
  ILLEGAL_VIDEO: 'ILLEGAL_VIDEO',
} as const;
