export const FILE_PATH = {
  USER_PROFILE: 'USER_PROFILE',
  USER_ADMISSION: 'USER_ADMISSION',
  USER_ACADEMIC_RECORD_APPLICATION: 'USER_ACADEMIC_RECORD_APPLICATION',
  CIRCLE_PROFILE: 'CIRCLE_PROFILE',
  POST: 'POST',
  CALENDAR: 'CALENDAR',
  EVENT: 'EVENT',
  ETC: 'ETC',
} as const;
